-- Script per popolare la tabella clients
-- I campi id, created_at, updated_at e is_active sono gestiti automaticamente dal database

INSERT INTO public.clients (full_name, email) VALUES
('Donatella Quadri', 'quadridonatella@gmail.com'),
('Sara Crystal Quispe Pascual', 'saracrystalquispepascual@gmail.com'),
('Paola Rapozzi', 'paolorapozzi@gmail.com'),
('Greta Colarich', 'colarich.greta@gmail.com'),
('Biagio Iorio', 'biorio06@gmail.com'),
('Viviana Viscovich', 'viviana.viscovich@gmail.com'),
('Nadia Atelj', 'nadiaatelj99@gmail.com'),
('Daniela Blasig', 'info.studiokalos@gmail.com'),
('Giovanni Visentini', 'giovannivisentini86@gmail.com'),
('Biagio Out', 'iorio.biagio@outlook.com'),
('Alice Tentor', 'alicetentor71@gmail.com'),
('Simona Albanese', 'simona-albanese@live.it'),
('Chiara Brandolin', 'chiara8.brandolin@gmail.com'),
('Alberto Deiuri', 'alberto.deiuri@gmail.com'),
('Luisa Blasig', 'luisa.blasig@gmail.com'),
('Paola Modesti', 'modestipaola63@gmail.com'),
('Francesca Vischi', 'francy.v06@gmail.com'),
('Michele Poletto', 'poletto@moviopoletto.com'),
('Cinzia Donda', 'cinzia.donda@gmail.com'),
('Leonardo De Simone', 'leonardo_desimone@libero.it'),
('Maya Colombo', 'colombomaya07@gmail.com'),
('Alessandra Albanese', 'alessandra.albanese23@gmail.com'),
('Jasmin Laurencic', 'jasmin.laurencic@gmail.com'),
('Anita Miceu', 'anita.miceu@gmail.com'),
('Francesca Baradel', 'francesca.baradel99@gmail.com'),
('JACQUELINE BURRI', 'jacqueline.burri88@gmail.com'),
('Gilda Aloisio', 'aloisiogilda@gmail.com'),
('Giulia Russian', 'russian.giulia@gmail.com'),
('Sara Lauri', 'saralauri@virgilio.it'),
('Luisa Movio', 'movio@moviopoletto.com'),
('Manuela Badin', 'manuela.badin68@gmail.com'),
('Annalisa Miceu', 'annalimic@yahoo.it'),
('Tommaso Ceschia', 'tommasoceschia@gmail.com'),
('Alessia Grosso', 'grosso.alessia98@gmail.com'),
('Giulia Starace', 'giulia.starace91@gmail.com'),
('Liala Dreos', 'liala.dreos@gmail.com'),
('Nicassio Chiara', 'ni.chiara@gmail.com'),
('Paola Boscarol', 'paoletta2867@gmail.com'),
('Elena Della Pietra', 'garecla5roele@gmail.com'),
('Daniele Poropat', 'danieleporopat@gmail.com'),
('Sara Consoli', 'consoli.sara96@gmail.com'),
('Martina Soban', 'martinasoban288@gmail.com'),
('Lucia Fabris', 'lucia.lfabris@gmail.com'),
('Margherita Sgorbissa', 'margheritasgorbissa@gmail.com'),
('Martina Macor', 'martimacor@live.it'),
('Cristina Patron', 'c.patron@libero.it'),
('Sara Caraceni', 'caracenisara@gmail.com'),
('Gaia Bandini', 'gaia.bandini77@gmail.com'),
('Anna Zorzet', 'zorzetanna@gmail.com'),
('ELENA GHIROTTO', 'elena.ghirotto@gmail.com'),
('Alessia Gon', 'gonalessia@icloud.com'),
('Valentina Alice Stangoni', 'valentinaalice.stangoni@gmail.com'),
('Teresa Donnarumma', 'tresy_17@hotmail.com'),
('Marianna Lattarulo', 'ira9381@gmail.com'),
('Achille Tresoldi', 'achtresol@libero.it'),
('Giulia Balestra', 'giuliabalestra@yahoo.it'),
('Roberto Corradini', 'roberto.corrad79@gmail.com'),
('Chiara Soraya Balsamini', 'chiarasoraya.balsamini59@gmail.com'),
('Greta Colarich', 'amministrazione.staccionata@gmail.com'),
('Alessandra Montanar', 'alesssmontanar@icloud.com'),
('Eleonora Molea', 'elemolea@yahoo.it'),
('Elvira Auramovic', 'elvirageorgiana@gmail.com'),
('Katia Tinta', 'katiatinta@gmail.com'),
('Giovanni Rodà', 'roda@libero.it'),
('Alessandra Simeone', 'alessandra.simeone@live.com'),
('Asia Abate', 'asiaabate17@gmail.com'),
('Elisa Voltolina', 'engie_hh@yahoo.it'),
('Desiree Figallo', 'zesisa2@gmail.com'),
('Barbara Sabatti', 'barbara.luca70@libero.it'),
('Anna Pagliaro', 'anna.paglia90@gmail.com'),
('Valentina Nicassio', 'valentinanic3@gmail.com')
ON CONFLICT DO NOTHING;

